## AIRBNB DATA ANALYSIS - Data Cleansing

In [ ]:
import pandas as pd 
import pymongo

In [3]:
mongodb_url = "" # Provide the mongodb_url from the 
client=pymongo.MongoClient(mongodb_url)
db=client.sample_airbnb
collection=db.listingsAndReviews

In [4]:
Extracted_data = []
for i in collection.find():
    data=dict(Id=i['_id'],
              Listing_url=i['listing_url'],
              Name=i.get("name"),
              Description=i.get("description"),
              Neighborhood_overview=i.get("neighborhood_overview"),
              House_rules=i.get("house_rules"),
              Property_type=i['property_type'],
              Room_type=i['room_type'],
              Bed_type=i['bed_type'],
              Minimum_nights=int(i['minimum_nights']),
              maximum_nights=int(i['maximum_nights']),
              cancellation_policy=i['cancellation_policy'],
              accommodates=int(i['accommodates']),
              bedrooms=i.get("bedrooms"),
              beds=i.get("beds"),
              number_of_reviews=int(i['number_of_reviews']),
              bathrooms=i.get('bathrooms'),
              amenities=', '.join(i['amenities']),
              price=i['price'],
              security_deposit=i.get('security_deposit'),
              cleaning_fee=i.get('cleaning_fee'),
              extra_people=i.get('extra_people'),
              guests_included=i['guests_included'],
              host_id=i['host']['host_id'],
              host_name=i['host']['host_name'],
              Street=i['address']['street'],
              Country=i['address']['country'],
              Country_code=i['address']['country_code'],
              longi=i['address']['location']['coordinates'][0],
              lati=i['address']['location']['coordinates'][1],
              Review_scores = i['review_scores'].get('review_scores_rating'),
              Is_exact_location=i['address']['location']['is_location_exact']
              )
    Extracted_data.append(data)

airbnb = pd.DataFrame(Extracted_data)

Dataset Info with datatype
To Find the null values in the dataset and their datatypes

In [7]:
airbnb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5555 entries, 0 to 5554
Data columns (total 32 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Id                     5555 non-null   object
 1   Listing_url            5555 non-null   object
 2   Name                   5555 non-null   object
 3   Description            5555 non-null   object
 4   Neighborhood_overview  5555 non-null   object
 5   House_rules            5555 non-null   object
 6   Property_type          5555 non-null   object
 7   Room_type              5555 non-null   object
 8   Bed_type               5555 non-null   object
 9   Minimum_nights         5555 non-null   int64
 10  maximum_nights         5555 non-null   int64
 11  cancellation_policy    5555 non-null   object
 12  accommodates           5555 non-null   int64
 13  bedrooms               5550 non-null   float64
 14  beds                   5542 non-null   float64
 15  number_of_reviews      5555 non-null   int64
 16  bathrooms              5545 non-null   object
 17  amenities              5555 non-null   object
 18  price                  5555 non-null   object
 19  security_deposit       3471 non-null   object
 20  cleaning_fee           4024 non-null   object
 21  extra_people           5555 non-null   object
 22  guests_included        5555 non-null   object
 23  host_id                5555 non-null   object
 24  host_name              5555 non-null   object
 25  Street                 5555 non-null   object
 26  Country                5555 non-null   object
 27  Country_code           5555 non-null   object
 28  longi                  5555 non-null   float64
 29  lati                   5555 non-null   float64
 30  Review_scores          4081 non-null   float64
 31  Is_exact_location      5555 non-null   bool
dtypes: bool(1), float64(5), int64(4), object(22)
memory usage: 1.3+ MB

Sample overview of the data

In [8]:
airbnb.head()

,Id,Listing_url,Name,Description,Neighborhood_overview,House_rules,Property_type,Room_type,Bed_type,Minimum_nights,...,guests_included,host_id,host_name,Street,Country,Country_code,longi,lati,Review_scores,Is_exact_location
0,10057447,https://www.airbnb.com/rooms/10057447,Modern Spacious 1 Bedroom Loft,"Prime location, amazing lighting and no annoyi...",,,Apartment,Entire home/apt,Real Bed,1,...,1,51612949,Konstantin,"Montréal, Québec, Canada",Canada,CA,-73.591110,45.518890,NaN,True
1,10030955,https://www.airbnb.com/rooms/10030955,Apt Linda Vista Lagoa - Rio,Quarto com vista para a Lagoa Rodrigo de Freit...,,,Apartment,Private room,Real Bed,1,...,1,51496939,Livia,"Rio de Janeiro, Rio de Janeiro, Brazil",Brazil,BR,-43.205047,-22.971951,NaN,True
2,1001265,https://www.airbnb.com/rooms/1001265,Ocean View Waikiki Marina w/prkg,A short distance from Honolulu's billion dolla...,You can breath ocean as well as aloha.,The general welfare and well being of all the ...,Condominium,Entire home/apt,Real Bed,3,...,1,5448114,David,"Honolulu, HI, United States",United States,US,-157.839190,21.286340,84.0,True
3,10047964,https://www.airbnb.com/rooms/10047964,Charming Flat in Downtown Moda,Fully furnished 3+1 flat decorated with vintag...,With its diversity Moda- Kadikoy is one of the...,"Be and feel like your own home, with total res...",House,Entire home/apt,Real Bed,2,...,1,1241644,Zeynep,"Kadıköy, İstanbul, Turkey",Turkey,TR,29.031330,40.985850,100.0,True
4,10006546,https://www.airbnb.com/rooms/10006546,Ribeira Charming Duplex,Fantastic duplex apartment with three bedrooms...,"In the neighborhood of the river, you can find...",Make the house your home...,House,Entire home/apt,Real Bed,2,...,6,51399391,Ana&Gonçalo,"Porto, Porto, Portugal",Portugal,PT,-8.613080,41.141300,89.0,False

Finding the missing values in the dataset

In [9]:
airbnb_null_val = airbnb.isnull().sum()
airbnb_null_val.sort_values(ascending=False)

security_deposit         2084
cleaning_fee             1531
Review_scores            1474
beds                       13
bathrooms                  10
bedrooms                    5
Id                          0
Listing_url                 0
Room_type                   0
Property_type               0
Bed_type                    0
Minimum_nights              0
Neighborhood_overview       0
House_rules                 0
Name                        0
Description                 0
number_of_reviews           0
accommodates                0
maximum_nights              0
cancellation_policy         0
price                       0
extra_people                0
guests_included             0
amenities                   0
host_id                     0
host_name                   0
Country                     0
Street                      0
Country_code                0
longi                       0
lati                        0
Is_exact_location           0
dtype: int64

# Data cleaning

In [22]:
airbnb.security_deposit.fillna(airbnb.security_deposit.mode()[0], inplace=True)
airbnb.cleaning_fee.fillna("0.0", inplace=True)
airbnb.Review_scores.fillna(airbnb.Review_scores.median(),inplace=True)
airbnb.beds.fillna(airbnb.beds.median(),inplace=True)
airbnb.bathrooms.fillna("0.0",inplace=True)
airbnb.bedrooms.fillna(airbnb.bedrooms.median(),inplace=True)

In [23]:
airbnb_null_val = airbnb.isnull().sum()
airbnb_null_val.sort_values(ascending=False)

Id                       0
Listing_url              0
Name                     0
Description              0
Neighborhood_overview    0
House_rules              0
Property_type            0
Room_type                0
Bed_type                 0
Minimum_nights           0
maximum_nights           0
cancellation_policy      0
accommodates             0
bedrooms                 0
beds                     0
number_of_reviews        0
bathrooms                0
amenities                0
price                    0
security_deposit         0
cleaning_fee             0
extra_people             0
guests_included          0
host_id                  0
host_name                0
Street                   0
Country                  0
Country_code             0
longi                    0
lati                     0
Review_scores            0
Is_exact_location        0
dtype: int64

Changing relevant data types

In [39]:
airbnb.price = airbnb.price.astype(str).astype(float)
airbnb.security_deposit = airbnb.security_deposit.astype(str).astype(float)
airbnb.cleaning_fee = airbnb.cleaning_fee.astype(str).astype(float)
airbnb.extra_people = airbnb.extra_people.astype(str).astype(float)
airbnb.guests_included = airbnb.guests_included.astype(str).astype(float)
airbnb.Review_scores = airbnb.Review_scores.astype('Int64')
airbnb.Country = airbnb.Country.replace('中国', 'China')
airbnb.drop(columns='Neighborhood_overview',inplace=True)

In [40]:
airbnb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5555 entries, 0 to 5554
Data columns (total 31 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Id                   5555 non-null   object
 1   Listing_url          5555 non-null   object
 2   Name                 5555 non-null   object
 3   Description          5555 non-null   object
 4   House_rules          5555 non-null   object
 5   Property_type        5555 non-null   object
 6   Room_type            5555 non-null   object
 7   Bed_type             5555 non-null   object
 8   Minimum_nights       5555 non-null   int64
 9   maximum_nights       5555 non-null   int64
 10  cancellation_policy  5555 non-null   object
 11  accommodates         5555 non-null   int64
 12  bedrooms             5555 non-null   float64
 13  beds                 5555 non-null   float64
 14  number_of_reviews    5555 non-null   int64
 15  bathrooms            5555 non-null   object
 16  amenities            5555 non-null   object
 17  price                5555 non-null   float64
 18  security_deposit     5555 non-null   float64
 19  cleaning_fee         5555 non-null   float64
 20  extra_people         5555 non-null   float64
 21  guests_included      5555 non-null   float64
 22  host_id              5555 non-null   object
 23  host_name            5555 non-null   object
 24  Street               5555 non-null   object
 25  Country              5555 non-null   object
 26  Country_code         5555 non-null   object
 27  longi                5555 non-null   float64
 28  lati                 5555 non-null   float64
 29  Review_scores        5555 non-null   Int64
 30  Is_exact_location    5555 non-null   bool
dtypes: Int64(1), bool(1), float64(9), int64(4), object(16)
memory usage: 1.3+ MB

# Treating the missing values for the string/object datatype.

In [41]:
airbnb['House_rules'].fillna("No House Rule is provided",inplace=True)
airbnb['Description'].fillna("No Description is provided",inplace=True)
airbnb['amenities'].fillna("No Amenities is provided",inplace=True)
airbnb['Name'].fillna("No Name is provided",inplace=True)

In [42]:
airbnb.head()

,Id,Listing_url,Name,Description,House_rules,Property_type,Room_type,Bed_type,Minimum_nights,maximum_nights,...,guests_included,host_id,host_name,Street,Country,Country_code,longi,lati,Review_scores,Is_exact_location
0,10057447,https://www.airbnb.com/rooms/10057447,Modern Spacious 1 Bedroom Loft,"Prime location, amazing lighting and no annoyi...",No House rules Provided,Apartment,Entire home/apt,Real Bed,1,1125,...,1.0,51612949,Konstantin,"Montréal, Québec, Canada",Canada,CA,-73.591110,45.518890,95,True
1,10030955,https://www.airbnb.com/rooms/10030955,Apt Linda Vista Lagoa - Rio,Quarto com vista para a Lagoa Rodrigo de Freit...,No House rules Provided,Apartment,Private room,Real Bed,1,1125,...,1.0,51496939,Livia,"Rio de Janeiro, Rio de Janeiro, Brazil",Brazil,BR,-43.205047,-22.971951,95,True
2,1001265,https://www.airbnb.com/rooms/1001265,Ocean View Waikiki Marina w/prkg,A short distance from Honolulu's billion dolla...,The general welfare and well being of all the ...,Condominium,Entire home/apt,Real Bed,3,365,...,1.0,5448114,David,"Honolulu, HI, United States",United States,US,-157.839190,21.286340,84,True
3,10047964,https://www.airbnb.com/rooms/10047964,Charming Flat in Downtown Moda,Fully furnished 3+1 flat decorated with vintag...,"Be and feel like your own home, with total res...",House,Entire home/apt,Real Bed,2,1125,...,1.0,1241644,Zeynep,"Kadıköy, İstanbul, Turkey",Turkey,TR,29.031330,40.985850,100,True
4,10006546,https://www.airbnb.com/rooms/10006546,Ribeira Charming Duplex,Fantastic duplex apartment with three bedrooms...,Make the house your home...,House,Entire home/apt,Real Bed,2,30,...,6.0,51399391,Ana&Gonçalo,"Porto, Porto, Portugal",Portugal,PT,-8.613080,41.141300,89,False

# Stats of the Dataset

In [43]:
airbnb.describe()

,Minimum_nights,maximum_nights,accommodates,bedrooms,beds,number_of_reviews,price,security_deposit,cleaning_fee,extra_people,guests_included,longi,lati,Review_scores
count,5555.000000,5.555000e+03,5555.000000,5555.000000,5555.000000,5555.000000,5555.000000,5555.000000,5555.000000,5555.000000,5555.000000,5555.000000,5555.000000,5555.0
mean,5.564356,1.382776e+06,3.505851,1.411341,2.071287,27.606481,278.766157,318.313771,68.147075,22.791899,1.747435,-6.623240,22.061230,93.6036
std,22.613861,5.256920e+07,2.297019,1.041547,1.617767,49.798376,842.215531,1284.484759,102.782629,69.331511,1.487352,90.525974,28.092112,7.779357
min,1.000000,1.000000e+00,1.000000,0.000000,0.000000,0.000000,9.000000,0.000000,0.000000,0.000000,1.000000,-159.678690,-34.088290,20.0
25%,1.000000,5.900000e+01,2.000000,1.000000,1.000000,1.000000,70.000000,0.000000,0.000000,0.000000,1.000000,-73.599530,20.724390,93.0
50%,2.000000,1.125000e+03,3.000000,1.000000,2.000000,5.000000,129.000000,0.000000,30.000000,0.000000,1.000000,-8.611420,40.727130,95.0
75%,3.000000,1.125000e+03,4.000000,2.000000,3.000000,32.000000,280.000000,250.000000,100.000000,20.000000,2.000000,29.019605,41.162755,98.0
max,1250.000000,2.147484e+09,16.000000,20.000000,25.000000,533.000000,48842.000000,39228.000000,2000.000000,2346.000000,16.000000,151.338980,45.665630,100.0

In [44]:
airbnb.to_csv("Airbnb.csv", index=False)